%YAML 1.2
--- 
name: "G6T9"
gpu: 0
dataset:
  num_chunks: 500_000_000
  allow_less_chunks: true
  train_ratio: 0.909
  sort_type: name
  input_train: 
    - '/home/raph/leela/data/train/training*/'
  input_test:
    - '/home/raph/leela/data/test/training*/'
  train_workers: 4
  test_workers: 2
  fast_chunk_loading: false
training:
    precision: half
    weight_decay: 0.0001
    swa: false
    swa_output: false
    swa_max_n: 10
    swa_steps: 100
    max_grad_norm: 3.0
    batch_size: 512
    num_batch_splits: 1
    #diff_focus_min: 0.025
    #diff_focus_slope: 3.0
    lookahead_optimizer: false
    renorm: true
    renorm_max_r: 1.0
    renorm_max_d: 0.0
    test_steps: 5_000
    disable_pb_checkpointing: false
    checkpoint_activations: false
    #num_test_positions : 50_000
    train_avg_report_steps: 1_000
    total_steps: 500_000
    checkpoint_steps: 1_000
    shuffle_size: 100_000
    warmup_steps: 1_000
    mask_legal_moves: true
    lr_values: # schedule is likely outdated
        - 0.00005
        - 0.00005
    lr_boundaries:
        - 100
    loss_weights:
        policy: 1.0
        policy_optimistic_st: 1.0
        policy_soft: 8.0 # loss is much smaller at optimum
        policy_opponent: 0.1
        policy_next: 0.1
        value_winner: 1.0
        value_q: 1.0
        value_q_cat: 0.1
        value_st: 1.0 # larger because mse loss
        value_q_err: 1.0  # both error weights should be the same
        value_st_err: 1.0
        value_st_cat: 0.1
        moves_left: 1.0
        reg: 1.0

    path: '/home/raph/leela/networks/'
    logs_path : '/home/raph/leela/logs'

    optimizer: nadam # sgd/nadam/rmsprop/adabelief
    beta_1: 0.9 
    beta_2: 0.999  # these values are only for Nadam
    epsilon: 0.0000001 # 1e-7
    sparse: false

    return_attn_wts: false
    return_activations: false

model:              
    embedding_size: 1024
    policy_embedding_size: 1024
    value_embedding_size: 128
    moves_left_embedding_size: 32                 # number of intermediate attention layers in the policy head
    encoder_layers: 15
    encoder_heads: 32                   # number of attention heads in encoder layers, emb // (32 or 64) recommended
                                         # with 64 memory is same as embedding, with 32 is double
    encoder_d_model: 1024                 # size of the Q, K, & V vectors in encoder layers -- divisible by encoder_heads
    encoder_dff: 1536                    # size of the expansion layer in encoder layer ffn
    policy_d_model: 1024                  # size of the query and key vectors in final attention layer
    policy_d_opt: 1024
    policy_d_soft: 256
    policy_d_opponent: 256
    policy_d_next: 256
    dropout_rate: 0.0                    # the dropout rate used for weight regularization of attention during training
                                        # makes memory 33 -> 39 GB on A100 as observed by Teck and Kovax

    embedding_dense_sz: 512           # number of params added is 50k times this number so care is needed

    value: "wdl"
    moves_left: "v1"
    input_type: "classic"

    # smolgen: more efficient version of fullgen, adds a lot of params
    use_smolgen: true
    smolgen_hidden_channels: 32
    smolgen_hidden_sz: 256
    smolgen_gen_sz: 256
    smolgen_activation: "swish"

    # RPE
    use_rpe_q: false
    use_rpe_k: false
    use_rpe_v: false

    # Gating
    use_logit_gating: false

    omit_qkv_biases: true 
    encoder_rms_norm: false
    policy_optimistic_st: true
    policy_opponent: true
    policy_next: true
    value_st: true
    value_q: true
    soft_policy: true
    categorical_value_buckets: 32
    soft_policy_temperature: 4.0

    # quantization
    quantize_activations: false
    quantize_weights: false
    quantize_activation_bits: 8
    quantize_weight_bits: 8
    quantize_channels: false
    rep_quant: false
    prenorm: false
    use_cnn_enc_ln: true

    gating_groups: 8
    gating_compressed: 32
    gating_hidden: 256
    gating_gen: 256

    blocks: ['G', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T']
    cnn_blocks_dims: [512, 512, 512, 512, 512, 512]
    cnn_dffs: [1536, 1536, 1536, 1536, 1536, 1536]
    se_ratio: 2
    
    #depthwise_masks: [[128, 128, 128],[128, 128, 128],[128, 128, 128],[128, 128, 128],[128, 128, 128],[128, 128, 128],[128, 128, 128],[128, 128, 128],[128, 128, 128]]
    #depthwise_ffn: [True, True, True, True, True, True, True, True, True]
    #depthwise_kernels: [3, 3, 3, 3, 3, 3, 3, 3, 3]
    #cnn_dffs: [576, 576]
    #se_ratio: 2
